/** @type {import('daisyui').Config} */
export default {
  themes: [
    {
      paletteNaturelle: {
        primary: "#4a6b4e", // vert doux
        secondary: "#e6c97a", // doré lumineux
        accent: "#bfa980", // ton terreux
        neutral: "#f5f5f5",
        "base-100": "#f5f5f5",
        info: "#a3c9a8",
        success: "#7bb274",
        warning: "#e6c97a",
        error: "#d4a59a",
        "--rounded-box": "1.5rem",
        "--rounded-btn": "1.25rem",
        "--rounded-badge": "1.25rem",
        "--tab-radius": "1.25rem",
        "--animation-btn": "0.25s",
        "--animation-input": "0.2s",
        "--btn-text-case": "capitalize",
        "--navbar-padding": "1.5rem",
        "--border-btn": "2px",
        fontFamily: {
          sans: ["Inter", "Montserrat", "sans-serif"],
          display: ["Playfair Display", "serif"],
        },
      },
    },
    "light",
    "dark",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthwave",
    "retro",
    "cyberpunk",
    "valentine",
    "halloween",
    "garden",
    "forest",
    "aqua",
    "lofi",
    "pastel",
    "fantasy",
    "wireframe",
    "black",
    "luxury",
    "dracula",
    "cmyk",
    "autumn",
    "business",
    "acid",
    "lemonade",
    "night",
    "coffee",
    "winter",
    "dim",
    "nord",
    "sunset",
  ],
}
